version: '3'
services:
  blog:
    build:
      context: ../kotlin-demo/
      args:
        - usedb=mysql
    expose:
    - "8080"
    depends_on:
    - "db"
  db:
    image: "sameersbn/mysql"
    environment:
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpass
    expose:
    - "3306"
  ui:
    build:
      context: ../nuxt-sandbox/
      dockerfile: Dev.Dockerfile
    volumes:
      - ../nuxt-sandbox/:/app
    environment:
      - GQL_URL=http://localhost:3000/graphql
    ports:
    - "8989:8989"
    depends_on:
      - "api"
  api:
    build:
      context: ../schema-stitching-demo/
    environment:
      - RUN_DELAY=20000
      - KIOSA_URL=http://blog:8080/graphql
    ports:
    - "3000:3000"
    depends_on:
      - "blog"
