apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 31978
status:
  loadBalancer: {}
