apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - env:
        - name: DB_CONNECTION_STRING
          value: mysql://db.default:$(DB_SERVICE_PORT)/dbname?autoReconnect=true&useSSL=false
        - name: DB_PASS
          value: dbpass # These are bad credentials we'll eventually want to migrate to using secrets (also avoid needing to keep this in sync with the DB deployment spec)
        - name: DB_USER
          value: dbuser
        - name: SPRING_PROFILES_ACTIVE
          value: mysql
        image: kiva/kiosa-dev:latest #We'll eventually want to be smarter with our tagging and not rely on latest
        name: blog
        ports:
        - containerPort: 8080
        resources: {}
        readinessProbe:
          httpGet:
            path: "/graphql?query=%7B__schema%7BqueryType%7Bname%7D%7D%7D"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: "/graphql?query=%7B__schema%7BqueryType%7Bname%7D%7D%7D"
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
      imagePullSecrets:
        - name: regcred # This will only work if you have set up a regcred secret containing Docker Hub credentials
      restartPolicy: Always
status: {}
