apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - env:
        - name: DB_NAME
          value: dbname # These are bad credentials we'll eventually want to migrate to using secrets
        - name: DB_PASS
          value: dbpass
        - name: DB_USER
          value: dbuser
        image: sameersbn/mysql # If we firm up on MySQL, we'll probably want to adapt to the actual MySQL image. I used this one for the convenient remote user + db setup via environment variables.
        name: db
        resources: {}
      restartPolicy: Always
status: {}
