apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - env:
        - name: GQL_URL
          value: "http://localhost:31978/graphql" # This maps back to the (a) local setup and (b) nodePort definition on the API service. What this really needs to be is the public address of the API server.
        image: kiva/kiosa-ui:latest
        name: ui
        ports:
        - containerPort: 8989
        resources: {}
        readinessProbe:
          httpGet:
            path: /
            port: 8989
          initialDelaySeconds: 15
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8989
          initialDelaySeconds: 30
          periodSeconds: 30
      restartPolicy: Always
status: {}
