apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ui-deployment
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - env:
        - name: GQL_URL
          value: "http://localhost:31978/graphql"
        image: nuxt:v0.1
        name: ui
        ports:
        - containerPort: 8989
        resources: {}
      restartPolicy: Always
status: {}
