apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  selector:
    app: ui
  type: NodePort # Again, NodePort running 1 replica for local convenience
  ports:
  - name: http
    port: 8989
    targetPort: 8989
status:
  loadBalancer: {}
